### ISSUE TITLE
String not in AMOS

### ISSUE THREAD

**Issue by dinism** [rwthanalytics/moodle-local_learning_analytics#4] opened 2021-07-31 12:29 UTC
I'm PT-PT translator
Some strings are missing in AMOS. 
Example:
[$string['navigation_link'] = 'Usage Statistics';](https://github.com/rwthanalytics/moodle-local_learning_analytics/blob/d3ef834ec4ec61edd49cae648ab9c1af69396d0c/lang/en/local_learning_analytics.php#L30)
Can you confirm this?
Thanks for thr plugin.

**Comment by thomasdondorf** [comment] 2021-08-16 09:17
I just checked in AMOS and yes, I can confirm this. Do you know why, though? I thought that Moodle AMOS would automatically take all language strings from the language files?

**Comment by dinism** [comment] 2021-08-16 16:32
I don't know WHY. Maybe you can contact someone that solve it. It's on ALL languages.

Thanks for the reply and the plugin.

**Comment by dinism** [comment] 2021-09-21 13:18
Any news about this issue?

**Comment by thomasdondorf** [comment] 2022-01-04 14:43
I'm not sure why this is happening. Even after some updates, there are still strings missing. I moved the question to the Moodle forum: https://lang.moodle.org/mod/forum/discuss.php?d=8455 Hopefully the Moodle devs can help.

**Comment by dinism** [comment] 2022-01-04 18:37
![imagem](https://user-images.githubusercontent.com/14828021/148107412-26dd7504-435c-4600-9720-920ed1c6c338.png)

**Comment by thomasdondorf** [comment] 2022-01-04 20:04
These are the (technical) IDs. I don't think they are translated anywhere, are they?

**Comment by dinism** [comment] 2022-01-04 21:59
In others plugins they are translated. I translated in logstore_lanalytics.

**Comment by dinism** [comment] 2022-01-04 22:57
**Other issue:**
![imagem](https://user-images.githubusercontent.com/14828021/148135094-39301bca-0d8e-4a3b-9ce8-3ae929508f54.png)
**Other issue:**
![imagem](https://user-images.githubusercontent.com/14828021/148135191-10add455-fa01-4712-8007-8b6fe8cd9b34.png)

**Comment by thomasdondorf** [comment] 2022-01-05 08:23
No, both of these are not hardcoded. It looks like your language pack just does not have the language strings for the keys and therefore falls back to English (default). Maybe your language pack is outdated or it just wasn't translated in AMOS?

If you want, you can check for yourself: The language string in the first image is [`setting_status_option_hide_link`](https://github.com/rwthanalytics/moodle-local_learning_analytics/blob/1ec6629405a375e10296d928521d9b3d6119fec2/lang/en/local_learning_analytics.php#L51). The language string for the user tour is [`tour_box_learners_link`](https://github.com/rwthanalytics/moodle-local_learning_analytics/blob/1ec6629405a375e10296d928521d9b3d6119fec2/lang/en/local_learning_analytics.php#L119).

**Comment by dinism** [comment] 2022-01-05 12:21
SORRY. YOU ARE RIGHT.
These 2 and **[`navigation_link`](https://github.com/rwthanalytics/moodle-local_learning_analytics/blob/1ec6629405a375e10296d928521d9b3d6119fec2/lang/en/local_learning_analytics.php#L30)** are the strings **MISSING in AMOS**.
In [`AMOS` ](https://lang.moodle.org/local/amos/view.php?t=1641384598&v=l&l=pt&c=local_learning_analytics&s&d)
![imagem](https://user-images.githubusercontent.com/14828021/148215793-c492114e-54c9-4f38-ae11-2838ee796acc.png)

In [`LANGUAGE FILE`](https://github.com/rwthanalytics/moodle-local_learning_analytics/blob/1ec6629405a375e10296d928521d9b3d6119fec2/lang/en/local_learning_analytics.php#L1)
I ordered the strings for better viewing. Look for the **YELLOW** strings ► **MISSING in AMOS**
![imagem](https://user-images.githubusercontent.com/14828021/148215634-341db2e2-ebc9-45fc-909d-86b388ed6369.png)

**Comment by thomasdondorf** [comment] 2022-01-05 17:27
Thanks! Really looking forward to an answer from the Moodle devs!
But I guess it's not a problem with this plugin but with AMOS.

**Comment by thomasdondorf** [comment] 2022-01-07 07:57
Problem [identified](https://lang.moodle.org/mod/forum/discuss.php?d=8455#p9885). The `_link` suffix has a special meaning in the strings...

Update is on the way.

**Closed** 2022-01-07 10:09 UTC

**Comment by thomasdondorf** [comment] 2022-01-07 10:45
Update is published in the Moodle store. Feel free to update the three strings in AMOS.

**Comment by dinism** [comment] 2022-01-07 13:53
[DONE](https://lang.moodle.org/local/amos/view.php?v=31100&t=1641563087&l=pt&c=local_learning_analytics). Waiting for AMOS update.
Thanks and keep the good work.
